name = str(input("ชื่อ \n"))
age = int(input("อายุ \n"))
idstudent = int(input("รหัสนักเรียน \n"))
Gradelevel = int(input("ระดับชั้น \n"))
nikename = str(input("ชื่อเล่น \n"))
high = float(input("ส่วนสูง \n"))
weight = float(input("น้ำหนัก \n"))
print("ชื่อ:"+name+"อายุ:"+str(age)+"ปี"+"\nรหัสประจำตัวนักเรียน:"+str(idstudent)+"ระดับชั้น:"+str(Gradelevel)+"\nชื่อเล่น:"+nikename+"\nส่วนสูง:"+str(high)+"เซนติเมตร"+"น้ำหนัก:"+str(weight)+"กิโลกรัม"+"\nส่วนสูง + น้ำหนัก ="+str(high+weight))
